# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  otel-collector:
    container_name: otel-collector
    hostname: otel-collector
    image: otel/opentelemetry-collector-contrib:0.155.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yml
    restart: unless-stopped
    environment:
      - DEPLOY_ENV=prod
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_AUTH_HEADER=${GRAFANA_CLOUD_AUTH_HEADER}
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    mem_limit: 256m
    cpus: 0.5
    networks:
      - observability

networks:
  observability:
    external: true
    name: observability
